# Generated by Django 3.2.4 on 2021-07-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integeration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmPassword',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
