# Generated by Django 3.2.4 on 2021-07-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integeration', '0003_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmPassword',
        ),
    ]
